version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    #volumes:
     # - database-data:/var/lib/postgresql/data/
  
  
  backend:
    build: ./backend
    container_name: backend_Tarea
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456

    depends_on:
      - database
    ports:
      - 8080:8080
    
    links:
      - database
  
  frontend:
    build: ./frontend
    container_name: frontend_tarea
    ports:
      - 3000:80
    
    depends_on:
    
      - backend

    links:
      - backend


volumes:
  database-data: